// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using order_book_backend.Data;

#nullable disable

namespace order_book_backend.Migrations
{
    [DbContext(typeof(OrderBookContext))]
    [Migration("20220312154316_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("order_book_backend.Model.OrderBook", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("OrderBook");
                });

            modelBuilder.Entity("order_book_backend.Model.OrderBookAsk", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderBookID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OrderBookID");

                    b.ToTable("Ask");
                });

            modelBuilder.Entity("order_book_backend.Model.OrderBookBid", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderBookID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OrderBookID");

                    b.ToTable("Bid");
                });

            modelBuilder.Entity("order_book_backend.Model.OrderBookAsk", b =>
                {
                    b.HasOne("order_book_backend.Model.OrderBook", null)
                        .WithMany("Asks")
                        .HasForeignKey("OrderBookID");
                });

            modelBuilder.Entity("order_book_backend.Model.OrderBookBid", b =>
                {
                    b.HasOne("order_book_backend.Model.OrderBook", null)
                        .WithMany("Bids")
                        .HasForeignKey("OrderBookID");
                });

            modelBuilder.Entity("order_book_backend.Model.OrderBook", b =>
                {
                    b.Navigation("Asks");

                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
